### ISSUE TITLE
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x4492eaa]

### ISSUE THREAD

**Issue by chaunsin** [hyperledger/fabric-sdk-go#223]
os:mac
golang:1.17.3
sdk:v1.0.0
error:
```shell
 [fabsdk/core] 2022/02/23 05:20:51 UTC - sw.getOptsByConfig -> DEBU Initialized SW cryptosuite
 [fabsdk/fab] 2022/02/23 05:20:51 UTC - sw.(*fileBasedKeyStore).createKeyStore -> DEBU Creating KeyStore at [/tmp/msp/keystore]...
 [fabsdk/fab] 2022/02/23 05:20:51 UTC - sw.(*fileBasedKeyStore).createKeyStore -> DEBU KeyStore created at [/tmp/msp/keystore].
 [fabsdk/fab] 2022/02/23 05:20:51 UTC - n/a -> DEBU KeyStore opened at [/tmp/msp/keystore]...done
 [fabsdk/fab] 2022/02/23 05:20:51 UTC - fab.(*EndpointConfig).loadEndpointConfiguration -> DEBU Client is: {Organization:org1 TLSCerts:{Client:{Key:{Path: Pem: bytes:[]} Cert:{Path: Pem: bytes:[]}}}}
 [fabsdk/fab] 2022/02/23 05:20:51 UTC - fab.(*EndpointConfig).loadEndpointConfiguration -> DEBU channels are: map[mychannel:{Orderers:[] Peers:map[peer0.org1.example.com:{EndorsingPeer:true ChaincodeQuery:true LedgerQuery:true EventSource:true} peer0.org2.example.com:{EndorsingPeer:true ChaincodeQuery:true LedgerQuery:true EventSource:true}] Policies:{QueryChannelConfig:{MinResponses:0 MaxTargets:0 RetryOpts:{Attempts:0 InitialBackoff:0s MaxBackoff:0s BackoffFactor:0 RetryableCodes:map[]}} Discovery:{MinResponses:0 MaxTargets:0 RetryOpts:{Attempts:4 InitialBackoff:1s MaxBackoff:0s BackoffFactor:0 RetryableCodes:map[]}} Selection:{SortingStrategy: Balancer: BlockHeightLagThreshold:0} EventService:{ResolverStrategy: MinBlockHeightResolverMode: Balancer: BlockHeightLagThreshold:0 PeerMonitor: ReconnectBlockHeightLagThreshold:0 PeerMonitorPeriod:0s}}}]
 [fabsdk/fab] 2022/02/23 05:20:51 UTC - fab.(*EndpointConfig).loadEndpointConfiguration -> DEBU organizations are: map[ordererorg:{MSPID:OrdererMSP CryptoPath:ordererOrganizations/example.com/users/{username}@example.com/msp Users:map[] Peers:[] CertificateAuthorities:[]} org1:{MSPID:Org1MSP CryptoPath:peerOrganizations/org1.example.com/users/{username}@org1.example.com/msp Users:map[] Peers:[peer0.org1.example.com peer0.org2.example.com] CertificateAuthorities:[]}]
 [fabsdk/fab] 2022/02/23 05:20:51 UTC - fab.(*EndpointConfig).loadEndpointConfiguration -> DEBU orderers are: map[orderer.example.com:{URL:orderer.example.com:7050 GRPCOptions:map[] TLSCACerts:{Path:${FABRIC_SDK_GO_PROJECT_PATH}/${CRYPTOCONFIG_FIXTURES_PATH}/ordererOrganizations/example.com/orderers/orderer.example.com/tls/tlscacerts/tls-localhost-9054-ca-orderer.pem Pem: bytes:[]}}]
 [fabsdk/fab] 2022/02/23 05:20:51 UTC - fab.(*EndpointConfig).loadEndpointConfiguration -> DEBU peers are: map[peer0.org1.example.com:{URL:peer0.org1.example.com:7051 GRPCOptions:map[] TLSCACerts:{Path:${FABRIC_SDK_GO_PROJECT_PATH}/${CRYPTOCONFIG_FIXTURES_PATH}/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem Pem: bytes:[]}} peer0.org2.example.com:{URL:peer0.org2.example.com:8051 GRPCOptions:map[] TLSCACerts:{Path:${FABRIC_SDK_GO_PROJECT_PATH}/${CRYPTOCONFIG_FIXTURES_PATH}/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem Pem: bytes:[]}}]
 [fabsdk/fab] 2022/02/23 05:20:51 UTC - fab.(*EndpointConfig).compileMatchers -> DEBU Matchers are: {matchers:map[]}
 [fabsdk/fab] 2022/02/23 05:20:51 UTC - fab.(*EndpointConfig).compileMatchers -> DEBU Entity matchers are not configured
 [fabsdk/msp] 2022/02/23 05:20:51 UTC - msp.(*IdentityConfig).loadIdentityConfigEntities -> DEBU Client is: {Organization:org1 Logging:{Level:debug} CryptoConfig:{Path:${FABRIC_SDK_GO_PROJECT_PATH}/${CRYPTOCONFIG_FIXTURES_PATH}} TLSCerts:{Client:{Key:{Path: Pem: bytes:[]} Cert:{Path: Pem: bytes:[]}} SystemCertPool:false} CredentialStore:{Path:/tmp/state-store CryptoStore:{Path:/tmp/msp}}}
 [fabsdk/msp] 2022/02/23 05:20:51 UTC - msp.(*IdentityConfig).loadIdentityConfigEntities -> DEBU organizations are: map[ordererorg:{MSPID:OrdererMSP CryptoPath:ordererOrganizations/example.com/users/{username}@example.com/msp Users:map[] Peers:[] CertificateAuthorities:[]} org1:{MSPID:Org1MSP CryptoPath:peerOrganizations/org1.example.com/users/{username}@org1.example.com/msp Users:map[] Peers:[peer0.org1.example.com peer0.org2.example.com] CertificateAuthorities:[]}]
 [fabsdk/msp] 2022/02/23 05:20:51 UTC - msp.(*IdentityConfig).loadIdentityConfigEntities -> DEBU certificateAuthorities are: map[]
 [fabsdk/msp] 2022/02/23 05:20:51 UTC - msp.(*IdentityConfig).compileMatchers -> DEBU Matchers are: {matchers:map[]}
 [fabsdk] 2022/02/23 05:20:51 UTC - fabsdk.initSDK -> DEBU SDK initialized successfully
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x4492eaa]

goroutine 1 [running]:
github.com/hyperledger/fabric-sdk-go/pkg/context.(*Client).Serialize(0xc000246400)
        <autogenerated>:1 +0x2a
github.com/hyperledger/fabric-sdk-go/pkg/fabsdk/provider/chpvdr.newCtxtCacheKey({0x64e9618, 0xc000246400})
        /Users/edy/go/pkg/mod/github.com/hyperledger/fabric-sdk-go@v1.0.0/pkg/fabsdk/provider/chpvdr/cachekey.go:25 +0x3f
github.com/hyperledger/fabric-sdk-go/pkg/fabsdk/provider/chpvdr.(*ChannelProvider).ChannelService(0xc00011fb18, {0x64e9618, 0xc000246400}, {0x4884ed0, 0x9})
        /Users/edy/go/pkg/mod/github.com/hyperledger/fabric-sdk-go@v1.0.0/pkg/fabsdk/provider/chpvdr/chprovider.go:69 +0x3c
github.com/hyperledger/fabric-sdk-go/pkg/context.NewChannel(0xc0002a00e0, {0x4884ed0, 0x3})
        /Users/edy/go/pkg/mod/github.com/hyperledger/fabric-sdk-go@v1.0.0/pkg/context/context.go:267 +0xfb
github.com/hyperledger/fabric-sdk-go/pkg/fabsdk.(*FabricSDK).ChannelContext.func1()
        /Users/edy/go/pkg/mod/github.com/hyperledger/fabric-sdk-go@v1.0.0/pkg/fabsdk/fabsdk.go:385 +0x4a
github.com/hyperledger/fabric-sdk-go/pkg/client/channel.New(0xc0002a00e0, {0xc0000c1ef8, 0x0, 0x4ffaaf0})
        /Users/edy/go/pkg/mod/github.com/hyperledger/fabric-sdk-go@v1.0.0/pkg/client/channel/chclient.go:54 +0x42
test-fabric/example/base/sdk.NewChannel(0x48a0184)
        /Users/edy/code/blockchain/fabric/example/base/sdk/channel.go:19 +0x4d
test-fabric/example/base/sdk.New(0xc0000001a0)
        /Users/edy/code/blockchain/fabric/example/base/sdk/sdk.go:42 +0x57
main.main()
        /Users/edy/code/blockchain/fabric/example/base/main.go:10 +0x1e
``
May I ask why?

**Comment by chaunsin** [comment]
me too
